"use client";
import "@aws-amplify/ui-react/styles.css";
import { ThemeProvider, Authenticator } from "@aws-amplify/ui-react";
import { Amplify } from "aws-amplify";
import { useEffect } from "react";

export default function Providers({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    // amplify_outputs.jsonが存在する場合のみ読み込み
    // Sandboxを起動すると自動生成されます
    async function configureAmplify() {
      try {
        // @ts-ignore - amplify_outputs.json is generated by `npx ampx sandbox`
        const outputs = await import("@/amplify_outputs.json");
        Amplify.configure(outputs.default || outputs);
      } catch (e) {
        console.warn("amplify_outputs.json not found. Run 'npx ampx sandbox' to generate it.");
      }
    }
    configureAmplify();
  }, []);

  return (
    <ThemeProvider>
      <Authenticator.Provider>{children}</Authenticator.Provider>
    </ThemeProvider>
  );
}
